name: my_portfolio
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'  # More flexible SDK constraint

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.10
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0  # Using a more stable version

flutter:
  uses-material-design: true

  assets:
    - assets/mypic.png